# Generated by Django 5.1.5 on 2025-04-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedwebsite',
            name='fake_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savedwebsite',
            name='legit_votes',
            field=models.IntegerField(default=0),
        ),
    ]
