# Generated by Django 5.1.5 on 2025-04-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_communitypost_id_alter_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(choices=[('legit', 'Legit'), ('fake', 'Fake')], max_length=10),
        ),
    ]
